package com.employee.portal.util;

public interface ServiceStaticValues {

	String RESPONSE_STATUS="STATUS";
	String RESPONSE_STATUS_SUCCESS="SUCCESS";
	String RESPONSE_PAYLOAD="PAYLOAD";
	String RESPONSE_MESSAGE="MESSAGE";
	String RESPONSE_STATUS_ERROR="ERROR";
	String RESPONSE_NO_DATA_SAVED="NOT ABLE TO SAVE DATA";
}
